### ISSUE TITLE
Timestamps

### ISSUE THREAD

**Issue by vorticalbox** [valamidev/json-mysql#2]
How do I deal with timestamps/dates? such as

```
{ date: '2019-04-29T17:10:10.100+0000' }
```

This will use VARCHAR and new Date will use INT

**Comment by valamidev** [comment]
Use something like this, to convert it into Unixtime:

```
var new_date = new Date(''2019-04-29T17:10:10.100+0000'');

console.log(new_date .getTime());
```

Or wait until I add some support for this kind of Date format.
